language: node_js

node_js:
  - 'node'

sudo: required

services:
  - docker

install:
  - npm install
  - npm install -g yarn

before_script:
  - git config --global user.name $USER_NAME
  - git config --global user.password $USER_PASSWORD

script:
  - git submodule init
  - git submodule update
  - yarn run build
  - yarn run deploy

deploy:
  provider: pages:git
  token: $GITHUB_TOKEN
  cleanup: true
  keep_history: false
  edge: true
