language: node_js

node_js:
  - 'node'

services:
  - docker

install:
  - npm install
  - npm install -g yarn

before_script:
  - git submodule init
  - git submodule update

script:
  - yarn run build

deploy:
  provider: pages
  cleanup: true
  token: $GITHUB_TOKEN
  keep_history: true
  deployment: 'prismagram-frontend/build'
  on:
    branch: master
