language: node_js

node_js:
  - 'node'

services:
  - docker

install:
  - sudo apt-get install git
  - npm install
  - npm install -g yarn

before_script:
  - git config --global user.name $USER_NAME
  - git config --global user.email $USER_EMAIL
  - git config --global user.password $USER_PASSWORD

script:
  - yarn run build
  - yarn deploy
