language: node.js
node_js:
  - 'node'

sudo: required

services:
  - docker

install:
  - npm install

script:
  - npm run build
  - npm run deploy

deploy:
  provider: pages:git
  token: $GITHUB_TOKEN
  edge: true
